# Generated by Django 2.2.3 on 2019-08-01 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('married_date', models.DateField(blank=True, null=True, verbose_name='married date')),
                ('married_location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('?', 'Unknown')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('birth_location', models.CharField(blank=True, max_length=100)),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='death date')),
                ('death_location', models.CharField(blank=True, max_length=100)),
                ('buried_date', models.DateField(blank=True, null=True, verbose_name='buried date')),
                ('buried_location', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Family')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Individual')),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Family')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Individual')),
            ],
        ),
    ]
