# Generated by Django 2.2.3 on 2019-08-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='family',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='individual',
        ),
        migrations.AddField(
            model_name='individual',
            name='parents',
            field=models.ManyToManyField(related_name='children_set', to='api.Individual'),
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
