# Generated by Django 2.2.3 on 2019-08-02 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190801_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='parents',
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('married_date', models.DateField(blank=True, null=True, verbose_name='married date')),
                ('married_location', models.CharField(blank=True, max_length=100)),
                ('partners', models.ManyToManyField(related_name='partner_in_families', to='api.Individual')),
            ],
        ),
        migrations.AddField(
            model_name='individual',
            name='child_in_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Family'),
        ),
    ]
