# Generated by Django 2.2.3 on 2019-08-04 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190802_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='child_in_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.Family'),
        ),
    ]
