# Generated by Django 2.2.4 on 2019-09-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190804_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='first_names',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='individual',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='individual',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('?', 'Unknown')], max_length=1),
        ),
    ]
