# Generated by Django 2.2.4 on 2019-09-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_family_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
