# Generated by Django 2.2.4 on 2019-10-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191012_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetrequest',
            old_name='username',
            new_name='user',
        ),
    ]
