# Generated by Django 2.2.4 on 2019-10-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_wordlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordList',
            new_name='FamilyNameList',
        ),
        migrations.RenameField(
            model_name='familynamelist',
            old_name='word',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='familynamelist',
            name='matching_individuals',
        ),
        migrations.AddField(
            model_name='familynamelist',
            name='matching_families',
            field=models.ManyToManyField(related_name='word_matches', to='api.Family'),
        ),
    ]
