# Generated by Django 2.2.4 on 2019-10-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191019_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familynamelist',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
