# Generated by Django 3.0 on 2019-12-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191019_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='married_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='married date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individual',
            name='baptism_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='baptism date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individual',
            name='birth_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='birth date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individual',
            name='buried_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='buried date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individual',
            name='death_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='death date'),
            preserve_default=False,
        ),
    ]
